src/PaginaDeCine/urls.py
from django.contrib import admin
from django.urls import path, include
from candy import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('candy.urls')),
]

src/candy/urls.py
from django.urls import path
from candy import views
from django.contrib.auth.views import LogoutView

app_name = 'candy'

urlpatterns = [
    path('', views.index, name='index'),
    path('candy/', views.candy_list, name='candy_list'),
    path('about/', views.about, name='about'),
    path('empleados/', views.empleados, name='empleados'),
    path('candy/update/<int:pk>/', views.candy_update, name='candy_update'),
    path('candy/delete/<int:pk>/', views.candy_delete, name='candy_delete'),
    path('login/', views.MiLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(template_name='candy/logout.html'), name='logout'),
    path('register/', views.MiRegisterView.as_view(), name='register'),

]

urlpatterns += [
    path('categorias/', views.empleados_categorias, name='categorias'),
    path('categorias/update/<int:pk>/', views.categoria_update, name='categoria_update'),
    path('categorias/delete/<int:pk>/', views.categoria_delete, name='categoria_delete'),
]

urlpatterns += [
    path('peliculas/', views.empleados_peliculas, name='peliculas'),
    path('peliculas/update/<int:pk>/', views.pelicula_update, name='pelicula_update'),
    path('peliculas/delete/<int:pk>/', views.pelicula_delete, name='pelicula_delete'),
]

src/candy/models.py
from django.db import models

class Peliculas(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_lanzamiento = models.DateField()

class CategoriaCandy(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nombre}'


class Candy(models.Model):
    categoria = models.ForeignKey(CategoriaCandy, on_delete=models.CASCADE, default=1)
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

src/candy/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CandyForm(forms.ModelForm):
    class Meta:
        model = models.Candy
        fields = "__all__"

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = models.CategoriaCandy
        fields = "__all__"

class PeliculaForm(forms.ModelForm):
    class Meta:
        model = models.Peliculas
        fields = "__all__"


class LoginForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ["username", "password"]

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {"username": ""}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ""
        self.fields['password2'].help_text = ""

src/candy/views.py
from django.shortcuts import render, redirect
from django.db.models import F
from .models import Candy, Peliculas, CategoriaCandy
from . import forms
from django.contrib.auth.views import LoginView
from .forms import LoginForm, RegisterForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib import messages


def index(request):
    busqueda = request.GET.get("busqueda")
    if busqueda:
        pelicula = Peliculas.objects.filter(titulo__icontains = busqueda)
    else:
        pelicula = Peliculas.objects.all().order_by('fecha_lanzamiento')
    context = {'pelicula': pelicula}
    return render(request, 'candy/index.html', context)

def about(request):
    return render(request, 'candy/about.html')

def candy_list(request):
    busqueda = request.GET.get("busqueda")
    if busqueda:
        candy = Candy.objects.filter(nombre__icontains = busqueda)
    else:
        candy = Candy.objects.all().order_by('nombre')
    context = {'candy': candy}
    return render(request, 'candy/candy_list.html', context)


def empleados(request):
    if request.method == "POST":
        form = forms.CandyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('candy:empleados')
    else:
        form = forms.CandyForm()
    candy = Candy.objects.all().order_by('categoria__nombre')
    return render(request, 'candy/empleados.html', {'form': form, 'candy': candy})

def candy_update(request, pk:int):
    query = Candy.objects.get(id=pk)
    if request.method == "GET":
        form = forms.CandyForm(instance=query)
    if request.method == "POST":
        form = forms.CandyForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('candy:empleados')
    return render(request, 'candy/candy_update.html', {'form': form})

def candy_delete(request, pk:int):
    query = Candy.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect('candy:empleados')
    return render(request, 'candy/candy_delete.html', {'query': query})





class MiLoginView(LoginView):
    template_name = 'candy/login.html'
    authentication_form = LoginForm
    next_page = reverse_lazy('candy:index')

    def form_valid(self, form):
        usuario = form.get_user()
        messages.success(self.request, f'Inicio de sesión exitoso. ¡Bienvenido {usuario.username}!')
        response = super().form_valid(form)
        return response

class MiRegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'candy/register.html'
    success_url = reverse_lazy('candy:login')

    def form_valid(self, form):
        messages.success(self.request, f'Registro exitoso. Inicie sesión aquí abajo.')
        return super().form_valid(form)







# CATEGORIAS. EDITAR Y ELIMINAR

def categorias(request):
    busqueda = request.GET.get("busqueda")
    if busqueda:
        categoria = CategoriaCandy.objects.filter(nombre__icontains = busqueda)
    else:
        categoria = CategoriaCandy.objects.all().order_by('nombre')
    context = {'categoria': categoria}
    return render(request, 'candy/categorias.html', context)

def empleados_categorias(request):
    categoria = CategoriaCandy.objects.all().order_by('nombre')
    if request.method == "GET":
        form = forms.CategoriaForm()
    if request.method == "POST":
        form = forms.CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('candy:categorias')
    return render(request, 'candy/categorias.html', {'form': form, 'categoria': categoria})

def categoria_update(request, pk:int):
    query = CategoriaCandy.objects.get(id=pk)
    if request.method == "GET":
        form = forms.CategoriaForm(instance=query)
    if request.method == "POST":
        form = forms.CategoriaForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('candy:categorias')
    return render(request, 'candy/categoria_update.html', {'form': form})

def categoria_delete(request, pk:int):
    query = CategoriaCandy.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect('candy:categorias')
    return render(request, 'candy/categoria_delete.html', {'query': query})






# PELICULAS. EDITAR Y ELIMINAR

def peliculas(request):
    busqueda = request.GET.get("busqueda")
    if busqueda:
        pelicula = Peliculas.objects.filter(titulo__icontains = busqueda)
    else:
        pelicula = Peliculas.objects.all().order_by('fecha_lanzamiento')
    context = {'pelicula': pelicula}
    return render(request, 'candy/peliculas.html', context)

def empleados_peliculas(request):
    peliculas = Peliculas.objects.all().order_by('fecha_lanzamiento')
    if request.method == "GET":
        form = forms.PeliculaForm()
    if request.method == "POST":
        form = forms.PeliculaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('candy:peliculas')
    return render(request, 'candy/peliculas.html', {'form': form, 'peliculas': peliculas})

def pelicula_update(request, pk:int):
    query = Peliculas.objects.get(id=pk)
    if request.method == "GET":
        form = forms.PeliculaForm(instance=query)
    if request.method == "POST":
        form = forms.PeliculaForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('candy:peliculas')
    return render(request, 'candy/pelicula_update.html', {'form': form})

def pelicula_delete(request, pk:int):
    query = Peliculas.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect('candy:peliculas')
    return render(request, 'candy/pelicula_delete.html', {'query': query})

src/candy/templates/candy/about.html
{% extends 'candy/base.html' %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>About</title>
    </head>
    <body>
        {% block content %}
        {% load static %}
            <h1>Acerca de mi</h1>
            <h3>Mirabel, Naren Nahuel</h3>
            <h5>Estudiante de Ingeniería Industrial en UNLaM</h5>
            <a href="https://www.linkedin.com/in/naren-mirabel/">
                <button>
                    <img src="{% static 'candy/linkedin.svg' %}" alt="linkedin" height="50px" width="100px">
                </button>
            </a>
        {% endblock content %}

    </body>
</html>

src/candy/templates/candy/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CINEMA</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'candy/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'candy/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        {% include 'componentes/nav.html' %}

        <!-- Page Content-->
        <main class="flex-shrink-0 py-5">
            <div class="container-fluid px-4 px-lg-5 mb-5 mt-auto">
                {% block content %}
                {% endblock content %}
            </div>
        </main>

        {% include 'componentes/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'candy/js/scripts.js' %}"></script>
    </body>
</html>

src/candy/templates/candy/candy_delete.html
{% extends 'candy/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Eliminar Candy</h1>
            <p class="text-center">¿Está seguro que desea eliminar el Candy: {{ query.nombre }}?</p>
            <form method="post" class="text-center">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Si, confirmo</button>
                <a href="{% url 'candy:empleados' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/candy/templates/candy/candy_list.html
{% extends 'candy/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-3">
    <h1 class="mb-4" style="font-size: 2.5em; font-weight: bold; color: #333;">Candy</h1>

    <div class="mb-3">
        <form method="get">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar producto" name="busqueda">
                <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </div>
        </form>
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for c in candy %}
            <tr>
                <td>{{ c.nombre }}</td>
                <td>{{ c.precio }} $</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

src/candy/templates/candy/candy_update.html
{% extends 'candy/base.html' %}

{% block content %}
{% load widget_tweaks %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Editar Candy</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/candy/templates/candy/categoria_delete.html
{% extends 'candy/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h1 class="text-center mb-4">Eliminar Categoría</h1>
                    <p class="text-center">¿Está seguro que desea eliminar la categoría: {{ query.nombre }}?</p>
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger mr-2">Si, confirmo</button>
                        <a href="{% url 'candy:categorias' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/candy/templates/candy/empleados.html
{% extends 'candy/base.html' %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio - Sector de empleados</title>
    </head>
    <body>
        {% block content %}
        {% load static %}
        <form method="post" class="mt-3">
            {% csrf_token %}
            <h2>Agregar candy</h2>
            <div class="mb-3">
                <label for="{{ form.categoria.id_for_label }}" class="form-label">Categoria:</label>
                <select class="form-select" id="{{ form.categoria.id_for_label }}" name="{{ form.categoria.name }}" required>
                    {% for categoria in form.categoria.field.queryset.all %}
                        <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre:</label>
                <input type="text" class="form-control" id="{{ form.nombre.id_for_label }}" name="{{ form.nombre.name }}" required {% if form.errors.nombre %}aria-describedby="nombreHelp" {% endif %}>
                {% if form.errors.nombre %}
                    <div id="nombreHelp" class="form-text text-danger">{{ form.errors.nombre }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="{{ form.precio.id_for_label }}" class="form-label">Precio:</label>
                <input type="number" class="form-control" id="{{ form.precio.id_for_label }}" name="{{ form.precio.name }}" required {% if form.errors.precio %}aria-describedby="precioHelp" {% endif %}>
                 {% if form.errors.precio %}
                    <div id="precioHelp" class="form-text text-danger">{{ form.errors.precio }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
        <br>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Candy</th>
                    <th>Precio</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
            {% for c in candy %}
                <tr>
                    <td>{{c.nombre}}</td>
                    <td>{{c.precio}}$</td>
                    <td>{{c.categoria}}</td>
                    <td><a href="{% url 'candy:candy_update' c.id %}" class="btn btn-sm btn-warning">Editar</a></td>
                    <td><a href="{% url 'candy:candy_delete' c.id %}" class="btn btn-sm btn-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% endblock content %}

src/candy/templates/candy/index.html
{% extends 'candy/base.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Cinema</title>
    </head>
    <body>


        {% block content %}
        {% load static %}

        <div class="row gx-4 gx-lg-5 align-items-center my-5">
            <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'candy/cine-portada.webp' %}" alt="..." /></div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">CineMirabel</h1>
                <p>🎬 ¡Vení a vivir la magia del cine como nunca antes! 🍿✨ En CineMirabel, te esperamos con las últimas películas en cartelera, la mejor calidad de imagen y sonido envolvente que te transportará al corazón de cada historia. Disfrutá de butacas súper cómodas, combos irresistibles de pochoclos y promos especiales para que vivas una experiencia única. 🎟️🔥 ¿Qué esperás? ¡Sacá tu entrada y sumergite en la emoción del séptimo arte! 🎥🍫</p>
                <a class="btn btn-primary" href="#!">Comprar entradas</a>
            </div>
        </div>
        <!-- Call to Action-->
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body"><h5 class="text-white m-0">🎬 Grandes historias te esperan en la pantalla grande. ¿Estás listo para la función? 🎬 </h5>
                <br>
                ¡Que no te falte nada para disfrutar la peli! 🍿🥤🧀⬇
            </div>
        </div>
        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Pochoclos</h2>
            <img class="img-fluid rounded mb-4" src="{% static 'candy/pochoclo.jpeg' %}" alt="..." style="height: 150px; width: 100%; object-fit: cover;"/>
            <p class="card-text">Nada mejor que el aroma irresistible del maíz recién explotado. Nuestros pochoclos son dorados, crocantes y dulces o salados —¡como más te gusten!—. Perfectos para compartir… o no 😉</p>
        </div>
    </div>
</div>
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Bebidas</h2>
            <img class="img-fluid rounded mb-4" src="{% static 'candy/pepsi.jpeg' %}" alt="..." style="height: 150px; width: 100%; object-fit: cover;"/>
            <p class="card-text">Refrescá cada escena con tu favorita: Pepsi, 7Up o Mirinda. Servidas bien frías, son el complemento ideal para acompañar los pochoclos o esos nachos que tanto te tientan.</p>
        </div>
    </div>
</div>
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Nachos</h2>
            <img class="img-fluid rounded mb-4" src="{% static 'candy/nachos.jpeg' %}" alt="..." style="height: 150px; width: 100%; object-fit: cover;"/>
            <p class="card-text">Crujientes, dorados y servidos con una generosa porción de queso cheddar derretido. Una combinación explosiva para los que buscan algo más que lo clásico.</p>
        </div>
    </div>
</div>
</div>

<div class="text-center">
    <a href="{% url 'candy:candy_list' %}" class="btn btn-primary btn-lg">Ir a Candy</a>
</div>

            {% for message in messages %}
                {{ message }}
            {% endfor %}

            <h2 class="text-center mb-4 mt-5" style="font-size: 2.5em; background-color: #343a40; color: white; padding: 10px;">Cartelera</h2>

            <div class="row">
                {% for p in pelicula %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ p.titulo }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ p.fecha_lanzamiento }}</h6>
                            <p class="card-text">{{ p.descripcion }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endblock content %}

    </body>
</html>

src/candy/templates/candy/login.html
{% extends 'candy/base.html' %}


{% block content %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Iniciar sesión</h2>
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Usuario:</label>
                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña:</label>
                            <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="password" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                        </div>
                    </form>
                    <p class="text-center mt-3">
                        ¿No tienes una cuenta? <a href="{% url 'candy:register' %}">Registrarse aquí</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/candy/templates/candy/logout.html
{% extends 'candy/base.html' %}

{% block content %}
{% load static %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title">Cerraste sesión correctamente</h2>
                        <p class="card-text">Gracias por tu visita.</p>
                        <a href="{% url 'candy:index' %}" class="btn btn-primary">Volver al inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/candy/templates/candy/pelicula_delete.html
{% extends 'candy/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h1 class="text-center mb-4">Eliminar Película</h1>
                    <p class="text-center">¿Está seguro que desea eliminar la película: {{ query.titulo }}?</p>
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger mr-2">Si, confirmo</button>
                        <a href="{% url 'candy:peliculas' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/candy/templates/candy/pelicula_update.html
{% extends 'candy/base.html' %}

{% block content %}
{% load widget_tweaks %}
{% load static %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Editar Película</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {% if field.name == 'fecha_lanzamiento' %}
                            {{ field|attr:"type:date"|add_class:"form-control" }}
                        {% else %}
                            {{ field|add_class:"form-control" }}
                        {% endif %}
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/candy/templates/candy/peliculas.html
{% extends 'candy/base.html' %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio - Sector de empleados</title>
    </head>
    <body>
        {% block content %}
        {% load static %}
            <form method="post" class="mt-3">
                {% csrf_token %}
                <h2>Agregar Pelicula</h2>
                <div class="mb-3">
                    <label for="{{ form.titulo.id_for_label }}" class="form-label">Título:</label>
                    <input type="text" class="form-control" id="{{ form.titulo.id_for_label }}" name="{{ form.titulo.name }}" required>
                </div>
                <div class="mb-3">
                    <label for="{{ form.descripcion.id_for_label }}" class="form-label">Descripción:</label>
                    <textarea class="form-control" id="{{ form.descripcion.id_for_label }}" name="{{ form.descripcion.name }}" rows="3" required></textarea>
                </div>
                <div class="mb-3">
                    <label for="{{ form.fecha_lanzamiento.id_for_label }}" class="form-label">Fecha de lanzamiento:</label>
                    <input type="date" class="form-control" id="{{ form.fecha_lanzamiento.id_for_label }}" name="{{ form.fecha_lanzamiento.name }}" required>
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
            <br>
            <table class="table table-striped">
                <thead>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="col-md-2">Peliculas</th>
                        <th class="col-md-4">Descripcion</th>
                        <th class="col-md-2 text-center">Fecha de estreno</th>
                        <th class="col-md-1">Editar</th>
                        <th class="col-md-1">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                {% for p in peliculas %}
                    <tr>
                        <td class="col-md-2">{{p.titulo}}</td>
                        <td class="col-md-4">{{p.descripcion}}</td>
                        <td class="col-md-2 text-center">{{p.fecha_lanzamiento}}</td>

                        <td class="col-md-1"><a href="{% url 'candy:pelicula_update' p.id %}" class="btn btn-sm btn-warning">Editar</a></td>
                        <td class="col-md-1"><a href="{% url 'candy:pelicula_delete' p.id %}" class="btn btn-sm btn-danger">Eliminar</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endblock content %}

    </body>
</html>

src/candy/templates/componentes/footer.html
<footer class="py-md-4 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Hecho en Coder: 2025</p></div>
</footer>

src/candy/templates/componentes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'candy:index' %}">CINEMA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                <li class="nav-item"><a class="nav-link active me-3" aria-current="page" href="{% url 'candy:about' %}">About</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link me-3" href="{% url 'candy:empleados' %}">Control Candy</a></li>
                    <li class="list-group-item"><a class="nav-link me-3" href="{% url 'candy:categorias' %}">Control Categorias</a></li>
                    <li class="list-group-item"><a class="nav-link me-3" href="{% url 'candy:peliculas' %}">Control Peliculas</a></li>
                    <form action="{% url 'candy:logout' %}" method="post" class="ms-2 me-2">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-secondary">Cerrar sesion</button>
                    </form>
                {% else %}
                    <li class="nav-item"><a class="nav-link me-3" href="{% url 'candy:candy_list' %}">Candy</a></li>
                    <li class="nav-item"><a class="nav-link me-3" href="{% url 'candy:login' %}">Sector Empleado</a></li>
                {% endif %}

                <form method="get" class="me-2">
                    <input type="text" name="busqueda" placeholder="Buscar..." class="form-control">
                </form>
            </ul>
        </div>
    </div>
</nav>